export const typeColors: { [key: string]: string } = {
  fire: "bg-red-500 text-white",
  water: "bg-blue-500 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-500 text-black",
  psychic: "bg-pink-500 text-white",
  ice: "bg-cyan-500 text-black",
  dragon: "bg-purple-500 text-white",
  dark: "bg-gray-800 text-white",
  fairy: "bg-pink-300 text-black",
  normal: "bg-gray-300 text-black",
  fighting: "bg-orange-500 text-white",
  rock: "bg-gray-600 text-white",
  ground: "bg-yellow-700 text-white",
  bug: "bg-green-700 text-white",
  ghost: "bg-purple-700 text-white",
  poison: "bg-purple-400 text-white",
  steel: "bg-gray-400 text-black",
  flying: "bg-blue-300 text-black",
};

export const typeWeaknesses: Record<string, string[]> = {
  normal: ["fighting"],
  fire: ["water", "rock", "ground"],
  water: ["electric", "grass"],
  electric: ["ground"],
  grass: ["fire", "ice", "poison", "flying", "bug"],
  ice: ["fire", "fighting", "rock", "steel"],
  fighting: ["flying", "psychic", "fairy"],
  poison: ["ground", "psychic"],
  ground: ["water", "grass", "ice"],
  flying: ["electric", "ice", "rock"],
  psychic: ["bug", "ghost", "dark"],
  bug: ["fire", "flying", "rock"],
  rock: ["water", "grass", "fighting", "ground", "steel"],
  ghost: ["ghost", "dark"],
  dragon: ["ice", "dragon", "fairy"],
  dark: ["fighting", "bug", "fairy"],
  steel: ["fire", "fighting", "ground"],
  fairy: ["poison", "steel"],
};
