export const typeColors: { [key: string]: string } = {
  fire: "bg-red-500 text-white",
  water: "bg-blue-500 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-500 text-black",
  psychic: "bg-pink-500 text-white",
  ice: "bg-cyan-500 text-black",
  dragon: "bg-purple-500 text-white",
  dark: "bg-gray-800 text-white",
  fairy: "bg-pink-300 text-black",
  normal: "bg-gray-300 text-black",
  fighting: "bg-orange-500 text-white",
  rock: "bg-gray-600 text-white",
  ground: "bg-yellow-700 text-white",
  bug: "bg-green-700 text-white",
  ghost: "bg-purple-700 text-white",
  poison: "bg-purple-400 text-white",
  steel: "bg-gray-400 text-black",
  flying: "bg-blue-300 text-black",
};
